FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-runtime

RUN apt-get update && apt-get install -y python3-dev build-essential

COPY ./requirements_cu117.txt .
RUN pip install -r requirements_vu117.txt

RUN python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt') "
RUN python -m spacy download en_core_web_sm

RUN zenodo_get 4054476
RUN tar -xvf openie6_data.tar.gz

# TAKES YEARS, do manually
#RUN zenodo_get 4055395
#RUN tar -xvf openie6_models.tar.gz
